### ISSUE TITLE
Add 90dns host file to bpack

### ISSUE THREAD

**Issue by carcaschoi** [petrusd10s/BPack#8]
As atmosphere 0.18.0 add a function of dns hosting, you may add this file into bpack to apply 90dns
[atmosphere.zip](https://github.com/petrusd10s/BPack/files/6324451/atmosphere.zip)

**Comment by petrusd10s** [comment]
90DNS slows down Tinfoil downloads, to protect the system from Nintendo, Serial Blanking is enabled by default (exosphere.ini)
